source 'https://rubygems.org'

gem 'colorize', '~> 0.8.1'
gem 'rspec'
gem 'rake'
gem 'cucumber', '~> 2.4'
gem 'selenium-webdriver', '~> 2.53'
gem 'capybara', '~> 2.10', '>= 2.10.1'
gem 'site_prism', '~> 2.9'
gem 'chromedriver-helper', '~> 1.0'
gem 'phantomjs', '~> 2.1'
gem 'poltergeist', '~> 1.11'
gem 'pry', '~> 0.10.4'
gem 'pry-byebug', '~> 3.4'
gem 'parallel_tests', '~> 2.10'