source 'https://rubygems.org'

gem 'colorize'
gem 'rspec'
gem 'rake'
gem 'cucumber', '~> 2.4'
gem 'selenium-webdriver', '~> 2.53'
gem 'capybara', '~> 2.10', '>= 2.10.1'
gem 'site_prism', '~> 2.9'
gem 'chromedriver-helper'
gem 'phantomjs', '~> 2.1'
gem 'poltergeist'
gem 'pry'
gem 'pry-byebug', '~> 3.4'
gem 'parallel_tests'